### ISSUE TITLE
JDK 10 breaks runAndNotify

### ISSUE THREAD

**Issue by alondhe** [OHDSI/OhdsiRTools#18]
Hi @schuemie,

~~It looks like R 3.5 only seems to work with JDK 10, but~~ installing JDK 10 seems to introduce a few errors, one of which is with runAndNotify:

```
java.lang.NoClassDefFoundError: javax/activation/DataHandler
	at org.apache.commons.mail.Email.createMimeMessage(Email.java:1832)
	at org.apache.commons.mail.Email.buildMimeMessage(Email.java:1268)
	at org.apache.commons.mail.Email.send(Email.java:1436)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at RJavaTools.invokeMethod(RJavaTools.java:386)
Caused by: java.lang.ClassNotFoundException
	at RJavaClassLoader.findClass(RJavaClassLoader.java:383)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	... 8 more
```

Perhaps this can help?

https://stackoverflow.com/questions/48750800/eclipse-java-lang-noclassdeffounderror-javax-activation-datahandler

Thanks,
Ajit

**Comment by schuemie** [comment]
FYI: ParallelLogger now has [an e-mail logger](https://ohdsi.github.io/ParallelLogger/articles/Logging.html#creating-an-e-mail-logger) that I prefer over `runAndNotify`. The main reason I like it better is that you can just add the logger at one point, and then all fatal errors from then on trigger an e-mail. (and I log a 'fatal' message when the process is done).
